[build-system]
requires = ["flit_core==3.9.0"]
build-backend = "flit_core.buildapi"

[project]
name = "gjob-pipeline"
version = "0.0.0"
description = "Data pipeline"
dependencies = [
  "astroid>=3.3.1",
  "cappa>=0.22.4",
  "devtools>=0.12.2",
  "more-itertools>=10.4.0",
  "pydantic>=2.9.1",
  "structlog>=25.4.0",
]
[project.scripts]
"gjob-pipeline" = "gjob_pipeline.__main__:main"

[tool.fawltydeps]
deps = ["packages/_pipeline/pyproject.toml"]
code = ["packages/_pipeline/src"]
ignore_undeclared = [
  "gjob_dev",
  "gjob_pipeline",
  "cachier",
  "context_models",
  "pipeline_helper",
]

[dependency-groups]
dev = ["colorama>=0.4.6", "dvc>=3.61.0", "rich>=14.0.0"]
