# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2025.1.3-37-g69d1951
_src_path: gh:softboiler/copier-pipeline
actions_runner: ubuntu-24.04
github_repo_name: gjob
package_name: gjob
project_description: Process Google Careers job alert emails
project_email: blake.naccarato@gmail.com
project_name: gjob
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
project_version: 2025.0.0
publish_project: true
python_version: '3.11'
year_of_project_creation: 2025
