# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.2.0-48-g59db0e7
_src_path: gh:softboiler/copier-pipeline
actions_runner: ubuntu-24.04
github_repo_name: gjob
package_name: gjob
project_description: Process Google Careers job alert emails
project_email: blake.naccarato@gmail.com
project_name: gjob
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
project_version: 0.0.3
python_version: '3.11'
year_of_project_creation: 2025
