stages:
  example:
    cmd: pwsh -Command "./j.ps1 gjob-pipeline stage example"
    deps:
      - packages/_pipeline/src/gjob/stages/example
      - docs/notebooks/example.ipynb
      - data/example
    outs:
      - data/example_out:
          persist: true
    params:
      - stage
