stages:
  convert:
    cmd: pwsh -Command "./j.ps1 gjob-pipeline stage convert"
    deps:
      - packages/_pipeline/src/gjob_pipeline/stages/convert
      - docs/notebooks/convert.ipynb
      - data/mail.json
    outs:
      - data/reqs.json:
          persist: true
    params:
      - stage
  example:
    cmd: pwsh -Command "./j.ps1 gjob-pipeline stage example"
    deps:
      - packages/_pipeline/src/gjob_pipeline/stages/example
      - docs/notebooks/example.ipynb
      - data/example
    outs:
      - data/example_out:
          persist: true
    params:
      - stage
  get_mail:
    cmd: pwsh -Command "./j.ps1 gjob-pipeline stage get-mail"
    deps:
      - packages/_pipeline/src/gjob_pipeline/stages/get_mail
      - data/mboxes
    outs:
      - data/mail.json:
          persist: true
    params:
      - stage
