stages:
  convert:
    cmd: pwsh -Command "./j.ps1 gjob-pipeline stage convert"
    deps:
      - packages/_pipeline/src/gjob_pipeline/stages/convert
      - docs/notebooks/convert.ipynb
      - data/mboxes
    outs:
      - data/reqs:
          cache: false
          persist: true
          push: false
    params:
      - stage
  example:
    cmd: pwsh -Command "./j.ps1 gjob-pipeline stage example"
    deps:
      - packages/_pipeline/src/gjob_pipeline/stages/example
      - docs/notebooks/example.ipynb
      - data/example
    outs:
      - data/example_out:
          persist: true
    params:
      - stage
  skip_cloud:
    cmd: pwsh -Command "./j.ps1 gjob-pipeline stage skip-cloud"
    outs:
      - data/mboxes:
          cache: false
          persist: true
          push: false
    params:
      - stage
