[build-system]
requires = ["flit_core==3.9.0"]
build-backend = "flit_core.buildapi"

[project]
name = "pipeline-helper"
version = "0.0.0"
description = "Data pipeline helper"
dependencies = [
  "cappa>=0.22.4",
  "dulwich>=0.23.0",
  "ipython>=8.26.0",
  "matplotlib>=3.7.2",
  "more-itertools>=10.4.0",
  "nbformat>=5.10.4",
  "pandas[hdf5,performance]>=2.2.2",
  "pint>=0.24.4",
  "ploomber-engine>=0.0.30",
  "pyarrow>=14.0.1",
  "pydantic-settings>=2.5.2",
  "pydantic>=2.9.1",
  "pyyaml>=6.0.2",
]

[tool.fawltydeps]
deps = ["packages/_pipeline-helper/pyproject.toml"]
code = ["packages/_pipeline-helper/src"]
ignore_undeclared = ["gjob_pipeline", "pipeline_helper", "cachier", "context_models"]
ignore_unused = [
  "pyarrow", # Used in `pipeline_helper.__init__`
]
