# Sync GitHub release notes with the changelog
name: "changerelease"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: True
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: ["main"]
    paths: ["CHANGELOG.md"]
defaults:
  run:
    shell: "pwsh"
jobs:
  env:
    uses: "./.github/workflows/env.yml"
  gh:
    needs: "env"
    runs-on: "${{ needs.env.outputs.actions_runner }}"
    outputs:
      latest_release: ${{ steps.gh.outputs.latest_release }}
    steps:
      - id: "gh"
        run: |
          $Env:GITHUB_OUTPUT = "latest_release=(./j.ps1 pkg-release-check)"
  changerelease:
    needs:
      - "env"
      - "gh"
    permissions:
      contents: "write"
    if: needs.env.outputs.project_version == needs.gh.outputs.latest_release
    continue-on-error: true
    runs-on: "${{ needs.env.outputs.actions_runner }}"
    steps:
      - uses: "dropseed/changerelease@3b121c9e98fa055f59a32b023cb4fd2325f4d9dc" # v1.6.0
        with:
          github_token: "${{ github.token }}"
          tag_prefix: ""
